// This file is auto-generated by controllers/bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// controllers/bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AnnouncementController from "controllers/announcement_controller"
application.register("announcement", AnnouncementController)

import AnnouncementHeightController from "controllers/announcement_height_controller"
application.register("announcement-height", AnnouncementHeightController)

import AnnouncementPreviewController from "controllers/announcement_preview_controller"
application.register("announcement-preview", AnnouncementPreviewController)

import ConfirmationModalController from "controllers/confirmation_modal_controller"
application.register("confirmation-modal", ConfirmationModalController)

import CsrfController from "controllers/csrf_controller"
application.register("csrf", CsrfController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import HelpWidgetController from "controllers/help_widget_controller"
application.register("help-widget", HelpWidgetController)

import MobileMenuController from "controllers/mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import NotificationsController from "controllers/notifications_controller"
application.register("notifications", NotificationsController)

import PaginationController from "controllers/pagination_controller"
application.register("pagination", PaginationController)

import PlanSelectionController from "controllers/plan_selection_controller"
application.register("plan-selection", PlanSelectionController)

import RegistrationValidationController from "controllers/registration_validation_controller"
application.register("registration-validation", RegistrationValidationController)

import RightSidebarController from "controllers/right_sidebar_controller"
application.register("right-sidebar", RightSidebarController)

import SidebarController from "controllers/sidebar_controller"
application.register("sidebar", SidebarController)

import TabsController from "controllers/tabs_controller"
application.register("tabs", TabsController)

import UserFormController from "controllers/user_form_controller"
application.register("user-form", UserFormController)
