// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmationModalController from "./confirmation_modal_controller"
application.register("confirmation-modal", ConfirmationModalController)

import CsrfController from "./csrf_controller"
application.register("csrf", CsrfController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HelpWidgetController from "./help_widget_controller"
application.register("help-widget", HelpWidgetController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)

import PlanSelectionController from "./plan_selection_controller"
application.register("plan-selection", PlanSelectionController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import UserFormController from "./user_form_controller"
application.register("user-form", UserFormController)
